name: SimpleDivisions
version: ${project.version}
main: me.xrexy.simpledivisions.SimpleDivisions
authors: [ xrexy ]

commands:
  division:
    description: Main command of SimpleDivisions
    usage: /<command>
    aliases: [ div ]

permissions:
  simpledivisions.*:
    default: op
    children:
      - simpledivisions.use
      - simpledivisions.me
      - simpledivisions.check
      - simpledivisions.give
      - simpledivisions.reset
      - simpledivisions.rewards
      - simpledivisions.updatetop
      - simpledivisions.top
      - simpledivisions.info
  simpledivisions.use:
    description: Use of the division command
    default: op
  simpledivisions.me:
    description: Allows player to view their own statistics
    default: op
  simpledivisions.check:
    description: Allows player to check other players statistics
    default: op
  simpledivisions.give:
    description: Allows admins to give other players points
    default: op
  simpledivisions.reset:
    description: Allows admins to reset other players statistics
    default: op
  simpledivisions.rewards:
    description: Allows player to view their own rewards
    default: op
  simpledivisions.updatetop:
    description: Allows admins to update the top list
    default: op
  simpledivisions.top:
    description: Allows player to view the top list
    default: op
  simpledivisions.info:
    description: Allows player to view the plugin information
    default: op